version: '3'
services:
  app:
    container_name: tag-and-find-app
    build:
      context: .
      dockerfile: Dockerfile-app
    networks:
      - tag-and-find
    restart: always
    depends_on:
      - nginx
  nginx:
    container_name: tag-and-find-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    networks:
      - tag-and-find
    ports:
      - 8101:8101
    restart: always

networks:
  tag-and-find:
    driver: bridge
