# ENTITIES DICTIONARY

DICT_WORD = {
    # Clean synonyms
    'clean': 'clean',
    'inmaculate': 'clean',
    'washed': 'clean',
    'blank': 'clean',
    'bright': 'clean',
    'clear': 'clean',
    'elegant': 'clean',
    'fresh': 'clean',
    'graceful': 'clean',
    'hygienic': 'clean',
    'immaculate': 'clean',
    'orderly': 'clean',
    'pure': 'clean',
    'simple': 'clean',
    'spotless': 'clean',
    'tidy': 'clean',
    'unblemished': 'clean',
    'neat': 'clean',
    # Clean antonyms
    'untidy': 'clean',
    'contaminated': 'clean',
    'dirty': 'clean',
    'dusty': 'clean',
    'filthy': 'clean',
    'greasy': 'clean',
    'grimy': 'clean',
    'messy': 'clean',
    'muddy': 'clean',
    'murky': 'clean',
    'nasty': 'clean',
    'polluted': 'clean',
    'unclean': 'clean',

    # Comfortable synonyms
    'cozy': 'comfortable',
    'comfortable': 'comfortable',
    'comfy': 'comfortable',
    'cushy': 'comfortable',
    'intimate': 'comfortable',
    'appropriate': 'comfortable',
    'complacent': 'comfortable',
    'convenient': 'comfortable',
    'easy': 'comfortable',
    'happy': 'comfortable',
    'healthy': 'comfortable',
    'loose': 'comfortable',
    'pleased': 'comfortable',
    'relaxed': 'comfortable',
    'satisfying': 'comfortable',
    'serene': 'comfortable',
    'snug': 'comfortable',
    'soft': 'comfortable',
    'useful': 'comfortable',
    # Comfortable antonyms
    'uncomfortable': 'comfortable',
    'annoying': 'comfortable',
    'awkward': 'comfortable',
    'bitter': 'comfortable',
    'difficult': 'comfortable',
    'distressing': 'comfortable',
    'hard': 'comfortable',
    'harsh': 'comfortable',
    'warm': 'comfortable',

    # Quiet synonyms
    'quiet': 'quiet',
    'muted': 'quiet',
    'peaceful': 'quiet',
    'reticent': 'quiet',
    'silent': 'quiet',
    'quieted': 'quiet',
    'calm': 'quiet',
    'peace': 'quiet',
    'relaxation': 'quiet',
    'serenity': 'quiet',
    'stillness': 'quiet',
    'tranquillity': 'quiet',
    'rest': 'quiet',
    'noiseless': 'quiet',
    # Quiet antonyms
    'loudness': 'quiet',
    'noise': 'quiet',
    'noisy': 'quiet',

    # Wonderful synonyms
    'admirable': 'wonderful',
    'amazing': 'wonderful',
    'astonishing': 'wonderful',
    'awesome': 'wonderful',
    'brilliant': 'wonderful',
    'cool': 'wonderful',
    'enjoyable': 'wonderful',
    'excellent': 'wonderful',
    'fabulous': 'wonderful',
    'fantastic': 'wonderful',
    'fine': 'wonderful',
    'incredible': 'wonderful',
    'magnificent': 'wonderful',
    'marvelous': 'wonderful',
    'outstanding': 'wonderful',
    'phenomenal': 'wonderful',
    'pleasant': 'wonderful',
    'pleasing': 'wonderful',
    'remarkable': 'wonderful',
    'sensational': 'wonderful',
    'strange': 'wonderful',
    'superb': 'wonderful',
    'surprising': 'wonderful',
    'terrific': 'wonderful',
    'tremendous': 'wonderful',
    'wondrous': 'wonderful',
    'wonderful': 'wonderful',
    # Wonderful antonyms
    'awful': 'wonderful',
    'crummy': 'wonderful',
    'dreadful': 'wonderful',
    'lousy': 'wonderful',
    'poor': 'wonderful',
    'rough': 'wonderful',
    'sad': 'wonderful',

    # Tasty synonyms
    'tasty': 'tasty',
    'appetizing': 'tasty',
    'delectable': 'tasty',
    'flavorful': 'tasty',
    'luscious': 'tasty',
    'pungent': 'tasty',
    'savory': 'tasty',
    'spicy': 'tasty',
    'yummy': 'tasty',
    # Tasty antonyms
    'bland': 'tasty',
    'distasteful': 'tasty',
    'dull': 'tasty',
    'flavorless': 'tasty',

    # Cheap synonyms
    'cheap': 'cheap',
    'economical': 'cheap',
    'low-cost': 'cheap',
    'low-priced': 'cheap',
    'inexpensive': 'cheap',
    # Cheap antonyms
    'expensive': 'cheap',
    'unreasonable': 'cheap',
    'costly': 'cheap',
    'overpriced': 'cheap',
    'pricey': 'cheap',
    'uneconomical': 'cheap',

    # Luxurious synonyms
    'luxurious': 'luxurious',
    'deluxe': 'luxurious',
    'extravagant': 'luxurious',
    'fancy': 'luxurious',
    'gorgeous': 'luxurious',
    'grand': 'luxurious',
    'imposing': 'luxurious',
    'lavish': 'luxurious',
    'lush': 'luxurious',
    'opulent': 'luxurious',
    'ostentatious': 'luxurious',
    'palatial': 'luxurious',
    'plush': 'luxurious',
    'posh': 'luxurious',
    'ritzy': 'luxurious',
    'splendid': 'luxurious',
    'stately': 'luxurious',
    'sumptuous': 'luxurious',
    'upscale': 'luxurious',
    # Luxurious antonyms
    'barren': 'luxurious',
    'common': 'luxurious',
    'destitute': 'luxurious',
    'inferior': 'luxurious',
    'insignificant': 'luxurious',
    'modest': 'luxurious',
    'ordinary': 'luxurious',
    'plain': 'luxurious',
    'reasonable': 'luxurious',
    'small': 'luxurious',
    'unimportant': 'luxurious',
    'unimpressive': 'luxurious',

    # Quick synonyms
    'active': 'quick',
    'agile': 'quick',
    'brief': 'quick',
    'brisk': 'quick',
    'cursory': 'quick',
    'energetic': 'quick',
    'expeditious': 'quick',
    'hasty': 'quick',
    'hurried': 'quick',
    'immediate': 'quick',
    'instantaneous': 'quick',
    'keen': 'quick',
    'nimble': 'quick',
    'rapid': 'quick',
    'sudden': 'quick',
    'express': 'quick',
    'swift': 'quick',
    # Quick antonyms
    'clumsy': 'quick',
    'delayed': 'quick',
    'idle': 'quick',
    'inactive': 'quick',
    'later': 'quick',
    'lazy': 'quick',
    'leisurely': 'quick',
    'slow': 'quick',
    'sluggish': 'quick',
    'unhurried': 'quick',

    # Gentle synonyms
    'gentle': 'gentle',
    'affable': 'gentle',
    'amiable': 'gentle',
    'benign': 'gentle',
    'compassionate': 'gentle',
    'considerate': 'gentle',
    'genial': 'gentle',
    'humane': 'gentle',
    'mellow': 'gentle',
    'moderate': 'gentle',
    'placid': 'gentle',
    'tame': 'gentle',
    'tender': 'gentle',
    'friendly': 'gentle',
    # Gentle antonyms
    'agitated': 'gentle',
    'callous': 'gentle',
    'cruel': 'gentle',
    'disagreeable': 'gentle',
    'hateful': 'gentle',
    'irritable': 'gentle',
    'loud': 'gentle',
    'merciless': 'gentle',
    'severe': 'gentle',
    'surly': 'gentle',
    'uncompassionate': 'gentle',
    'unfeeling': 'gentle',
    'unfriendly': 'gentle',
    'unhappy': 'gentle',
    'unkind': 'gentle',
    'violent': 'gentle',

}
