# ENTITIES
DICT_WORD = {
    # Clean synonyms
    'clean': 'clean',
    'inmaculate': 'clean',
    'washed': 'clean',
    'blank': 'clean',
    'bright': 'clean',
    'clear': 'clean',
    'elegant': 'clean',
    'fresh': 'clean',
    'graceful': 'clean',
    'hygienic': 'clean',
    'immaculate': 'clean',
    'orderly': 'clean',
    'pure': 'clean',
    'simple': 'clean',
    'spotless': 'clean',
    'tidy': 'clean',
    'unblemished': 'clean',
    'neat': 'clean',
    # Clean antonyms
    'untidy': 'clean',
    'contaminated': 'clean',
    'dirty': 'clean',
    'dusty': 'clean',
    'filthy': 'clean',
    'greasy': 'clean',
    'grimy': 'clean',
    'messy': 'clean',
    'muddy': 'clean',
    'murky': 'clean',
    'nasty': 'clean',
    'polluted': 'clean',
    'unclean': 'clean',

    # Comfortable synonyms
    'cozy': 'comfortable',
    'comfortable': 'comfortable',
    'comfy': 'comfortable',
    'cushy': 'comfortable',
    'intimate': 'comfortable',
    'appropriate': 'comfortable',
    'complacent': 'comfortable',
    'convenient': 'comfortable',
    'easy': 'comfortable',
    'happy': 'comfortable',
    'healthy': 'comfortable',
    'loose': 'comfortable',
    'pleased': 'comfortable',
    'relaxed': 'comfortable',
    'satisfying': 'comfortable',
    'serene': 'comfortable',
    'snug': 'comfortable',
    'soft': 'comfortable',
    'useful': 'comfortable',
    # Comfortable antonyms
    'uncomfortable': 'comfortable',
    'annoying': 'comfortable',
    'awkward': 'comfortable',
    'bitter': 'comfortable',
    'difficult': 'comfortable',
    'distressing': 'comfortable',
    'hard': 'comfortable',
    'harsh': 'comfortable',
    'warm': 'comfortable',

    # Quiet synonyms
    'quiet': 'quiet',
    'muted': 'quiet',
    'peaceful': 'quiet',
    'reticent': 'quiet',
    'silent': 'quiet',
    'quieted': 'quiet',
    'calm': 'quiet',
    'peace': 'quiet',
    'relaxation': 'quiet',
    'serenity': 'quiet',
    'stillness': 'quiet',
    'tranquillity': 'quiet',
    'rest': 'quiet',
    'noiseless': 'quiet',
    # Quiet antonyms
    'loudness': 'quiet',
    'noise': 'quiet',
    'noisy': 'quiet',

    # Wonderful synonyms
    'admirable': 'wonderful',
    'amazing': 'wonderful',
    'astonishing': 'wonderful',
    'awesome': 'wonderful',
    'brilliant': 'wonderful',
    'cool': 'wonderful',
    'enjoyable': 'wonderful',
    'excellent': 'wonderful',
    'fabulous': 'wonderful',
    'fantastic': 'wonderful',
    'fine': 'wonderful',
    'incredible': 'wonderful',
    'magnificent': 'wonderful',
    'marvelous': 'wonderful',
    'outstanding': 'wonderful',
    'phenomenal': 'wonderful',
    'pleasant': 'wonderful',
    'pleasing': 'wonderful',
    'remarkable': 'wonderful',
    'sensational': 'wonderful',
    'strange': 'wonderful',
    'superb': 'wonderful',
    'surprising': 'wonderful',
    'terrific': 'wonderful',
    'tremendous': 'wonderful',
    'wondrous': 'wonderful',
    'wonderful': 'wonderful',
    # Wonderful antonyms
    'awful': 'wonderful',
    'crummy': 'wonderful',
    'dreadful': 'wonderful',
    'lousy': 'wonderful',
    'poor': 'wonderful',
    'rough': 'wonderful',
    'sad': 'wonderful'
}
